---
roles:
  - name: geerlingguy.apache
    version: 4.0.0
  - name: geerlingguy.php
    version: 6.0.0
  - name: geerlingguy.apache-php-fpm
    version: 1.1.0
  - name: geerlingguy.postgresql
    version: 3.5.2